# Generated by Django 5.0.7 on 2024-08-23 11:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="address",
            fields=[
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("created_by", models.IntegerField(default=1)),
                ("last_updated_at", models.DateTimeField(null=True)),
                ("last_updated_by", models.IntegerField(null=True)),
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_line", models.TextField()),
                ("second_line", models.TextField()),
                ("third_line", models.TextField()),
                ("town_city", models.TextField()),
                ("county", models.TextField()),
                ("country", models.TextField()),
                ("postcode", models.TextField()),
            ],
            options={
                "db_table": "address",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PyrlUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=120, unique=True)),
                ("password", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_root", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_names", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "mfa_enabled",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="MFA Enabled"
                    ),
                ),
                (
                    "mfa_type",
                    models.CharField(
                        blank=True,
                        choices=[("sm", "sms"), ("em", "email")],
                        max_length=2,
                        null=True,
                        verbose_name="MFA Type",
                    ),
                ),
                (
                    "mfa_code",
                    models.IntegerField(blank=True, null=True, verbose_name="MFA Code"),
                ),
                ("address_line_1", models.CharField(max_length=100)),
                ("address_line_2", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.company"
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="system_user",
            fields=[
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("created_by", models.IntegerField(default=1)),
                ("last_updated_at", models.DateTimeField(null=True)),
                ("last_updated_by", models.IntegerField(null=True)),
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_names", models.TextField()),
                ("middle_names", models.TextField()),
                ("last_names", models.TextField()),
                ("dob", models.DateField()),
                ("password", models.TextField()),
                ("root_user", models.BooleanField()),
                ("contact_email_address", models.TextField()),
                ("contact_phone_number", models.TextField(max_length=11)),
                (
                    "address_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.address",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.company"
                    ),
                ),
            ],
            options={
                "db_table": "system_users",
                "abstract": False,
            },
        ),
    ]
