# Generated by Django 5.0.7 on 2024-08-26 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pyrluser",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="mfa_code",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="mfa_enabled",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="mfa_type",
        ),
        migrations.RemoveField(
            model_name="pyrluser",
            name="postal_code",
        ),
    ]
