# Generated by Django 5.0.3 on 2024-11-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_pyrluser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyrluser',
            name='username',
        ),
    ]
