# Generated by Django 5.0.3 on 2024-11-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pyrlclient'),
        ('user_management', '0004_remove_pyrluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyrluser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='company_id',
        ),
        migrations.AddField(
            model_name='pyrluser',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient'),
        ),
        migrations.AddField(
            model_name='system_user',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pyrluser',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
