# Generated by Django 5.0.3 on 2024-11-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_pyrluser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyrluser',
            name='is_client_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='system_user',
        ),
    ]
