# Generated by Django 5.0.3 on 2024-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_pyrluser_is_client_admin_delete_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyrluser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='pyrluser',
            table='system_users',
        ),
    ]
