# Generated by Django 5.0.3 on 2024-12-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(editable=False, max_length=3, unique=True)),
                ('entity_description', models.TextField()),
            ],
            options={
                'db_table': 'legal_entity',
                'abstract': False,
            },
        ),
    ]
