# Generated by Django 5.0.3 on 2024-12-03 22:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.IntegerField(default=1)),
                ('last_updated_at', models.DateTimeField(null=True)),
                ('last_updated_by', models.IntegerField(null=True)),
                ('relationship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.entitytypes')),
            ],
            options={
                'db_table': 'relationship',
                'abstract': False,
            },
        ),
    ]
