# Generated by Django 5.0.3 on 2024-12-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitytypes',
            old_name='entity_description',
            new_name='description',
        ),
    ]
