# Generated by Django 5.0.3 on 2024-12-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_rename_entity_description_entitytypes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.entitytypes', to_field='entity_id'),
        ),
    ]
