# Generated by Django 5.0.3 on 2025-01-08 16:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_remove_pyrlclient_created_at_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.IntegerField(default=1)),
                ('last_updated_at', models.DateTimeField(null=True)),
                ('last_updated_by', models.IntegerField(null=True)),
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'project',
                'abstract': False,
            },
        ),
    ]
