# Generated by Django 5.0.3 on 2025-01-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
