# Generated by Django 5.0.7 on 2024-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="request_analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default="ERROR", verbose_name="Request ID"),
                ),
                (
                    "request_time",
                    models.DecimalField(
                        decimal_places=16,
                        default=0.0,
                        max_digits=32,
                        max_length=100,
                        verbose_name="Request Exec Time",
                    ),
                ),
                (
                    "request_page",
                    models.TextField(default="ERROR", verbose_name="Request Path"),
                ),
            ],
            options={
                "db_table": "request_analytics",
            },
        ),
    ]
