# Generated by Django 5.0.3 on 2025-01-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0005_transactiontype_full_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference_description', models.TextField()),
                ('net', models.DecimalField(decimal_places=4, max_digits=15)),
                ('vat_type', models.CharField(choices=[('ZER', 'Zero'), ('TEN', '10%'), ('FUL', '20%')], default='FUL')),
                ('vat', models.DecimalField(decimal_places=4, max_digits=15)),
                ('gross', models.DecimalField(decimal_places=4, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.account')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.transactiontype')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
