# Generated by Django 5.0.3 on 2025-01-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vat_type',
            field=models.CharField(choices=[('ZER', '0%'), ('TEN', '10%'), ('FUL', '20%')], default='FUL'),
        ),
    ]
