# Generated by Django 5.0.3 on 2025-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_vat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gross',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15),
        ),
    ]
