# Generated by Django 5.0.3 on 2025-01-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_gross_alter_transaction_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(blank=True, default='2025-01-05'),
            preserve_default=False,
        ),
    ]
