# Generated by Django 5.0.3 on 2025-03-01 23:39

import _hashlib
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_remove_pyrlclient_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api_key', models.TextField(default=_hashlib.openssl_sha256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient')),
            ],
        ),
    ]
