# Generated by Django 5.0.3 on 2025-03-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apikey',
            table='api_key',
        ),
    ]
