# Generated by Django 5.0.3 on 2025-02-04 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_rename_plaid_public_token_customer_plaid_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('mask', models.TextField()),
                ('bank_type', models.TextField()),
                ('bank_subtype', models.TextField()),
                ('verification_status', models.TextField()),
                ('class_type', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
