# Generated by Django 5.0.3 on 2025-02-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bankinstitution_bankaccount_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='class_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='verification_status',
            field=models.TextField(null=True),
        ),
    ]
