# Generated by Django 5.0.3 on 2025-02-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_bankaccount_class_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_account',
        ),
        migrations.AlterModelTable(
            name='bankinstitution',
            table='bank_institution',
        ),
    ]
