# Generated by Django 5.0.3 on 2025-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_bankaccount_table_alter_bankinstitution_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='ENA', max_length=3),
        ),
    ]
