# Generated by Django 5.0.3 on 2024-04-27 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="invoice",
            fields=[
                (
                    "pid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("invoice_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_of_invoice", models.DateField()),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.pyrl_company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="invoice_product",
            fields=[
                (
                    "pid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("date_of_order", models.DateField()),
                ("item_description", models.CharField(max_length=100)),
                ("price_per_item", models.DecimalField(decimal_places=2, max_digits=5)),
                ("quantity", models.IntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "invoice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.pyrl_product",
                    ),
                ),
            ],
        ),
    ]
