# Generated by Django 5.0.7 on 2024-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(default="Invoice 2024-08-24 to Alex", max_length=40),
        ),
    ]
