# Generated by Django 5.0.7 on 2024-08-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0003_alter_invoice_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="note",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoicing.note",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="terms_conditions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoicing.terms_conditions",
            ),
        ),
    ]
