# Generated by Django 5.0.7 on 2024-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0004_alter_invoice_note_alter_invoice_terms_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(default="Invoice 2024-09-01 to Alex", max_length=40),
        ),
    ]
