# Generated by Django 5.0.7 on 2024-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0005_alter_invoice_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(default="Invoice 2024-11-12 to Alex", max_length=40),
        ),
    ]
