# Generated by Django 5.0.7 on 2024-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0007_alter_invoice_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(default="Invoice 2024-11-14 to Alex", max_length=40),
        ),
    ]
