# Generated by Django 5.0.3 on 2024-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_alter_invoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(default='Invoice 2024-11-19 to Alex', max_length=40),
        ),
    ]
