# Generated by Django 5.0.3 on 2024-11-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pyrlclient'),
        ('invoicing', '0009_alter_invoice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient'),
            preserve_default=False,
        ),
    ]
