# Generated by Django 5.0.3 on 2025-01-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_alter_invoice_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='invoice_product_link',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoice_product_link',
            old_name='product_id',
            new_name='product',
        ),
    ]
