"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

# Define constants for settings

ENV_STAGING = "STAGING"
ENV_PROD = "PROD"
ENV_DEV = "DEV"

if 'ENV' not in os.environ:
    ENV = ENV_DEV
else: ENV = os.environ["ENV"]

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

INTERNAL_IPS = [
    "127.0.0.1",
]

NAME = "Pyrl"
DIVIDER = "@"
SITE_TITLE = NAME

if ENV == ENV_STAGING or ENV == ENV_PROD:
    DOMAIN = 'pyrl.uk'
else:
    DOMAIN = 'localpyrl.uk:8000'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^glq(et8ig!4jj^s!f$^)_7y(-@%2jzb3l*9+7wm5hsc$6-6!8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/auth/login/'

TAILWIND_APP_NAME = "theme"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.forms',
    'tailwind',
    "theme",
    'core',
    'ui',
    'analytics',
    'user_management',
    'invoicing',
    'base',
    'main_app',
    'jquery',
    'products',
    'utils',
    'jobs',
    'customers',
    'vendors',
    'chart_of_accounts',
    'opportunities',
    'aws',
    'projects',
    'storages',
    'transaction',
    'banking',
    'api_application',
]

class WEEKDAYS:
    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6

RELOAD = False

NO_ANALYTICS = [
    '/static/',
    '/__reload__/events/'
]

MAIN_PAGE_PATH_ID = '/home/'

ANALYTICS_DAYS = [
    WEEKDAYS.FRIDAY,
    WEEKDAYS.SATURDAY,
    WEEKDAYS.SUNDAY
]



ANALYTICS_CONFIG = {
    'NO_ANALYTICS': NO_ANALYTICS,
    'VALID_WEEKDAYS': ANALYTICS_DAYS
}

# AUTHENTICATION_BACKENDS = ['core.backends.backends.MyBackend']

# email
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'base@pyrl.online'
# EMAIL_HOST_PASSWORD = '@e5[8Y6,C03O'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "core.middlewares.middleware.add_parent_client_to_request",
    # "utils.middlewares.middleware.determine_ajax",
    "analytics.middlewares.middleware.get_request_analytics",
    "core.middlewares.domain_middlewares.print_domain",
    # "core.middlewares.middleware.OneSessionPerUserMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.user_context",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databasess

DB_NAME = 'localpyrl'
DB_USER = 'postgres'
DB_PASSWORD = ''
DB_IP = '127.0.0.1'
DB_PORT = '5432'
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'
if ENV == ENV_DEV:
    with open(os.path.join(BASE_DIR, 'db.password.txt'), 'r') as db_password_file:
        data = db_password_file.read()
        DB_PASSWORD = data

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql',
       'NAME': DB_NAME,
       'USER': DB_USER,
       'PASSWORD': DB_PASSWORD,
       'HOST': DB_IP,
       'PORT': DB_PORT,
   }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = 'user_management.PyrlUser'


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DOMAIN_PATHS =  {
                    'home': 'home', 
                    'root': '/'
                }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "theme/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

THEME_HIGHLIGHT = '#1a1ae8'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.user_context",
            ],
        }
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis database 1
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Forms and Widgets

## settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        '__main__': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# AWS S3 Settings
AWS_ACCESS_KEY_ID = 'AKIAX5ZI6F2N545ZX56D'
AWS_SECRET_ACCESS_KEY = 'rwN1V31tA2NMDzjceOG/CybFDKbi0VYa6/X32FgP'
AWS_STORAGE_BUCKET_NAME = 'pyrl-invoice-documents'
AWS_S3_REGION_NAME = 'eu-west-2'  # e.g., 'us-west-1'
AWS_S3_FILE_OVERWRITE = True 
AWS_DEFAULT_ACL = 'private' 
AWS_QUERYSTRING_AUTH = True

# S3 Media Files Configuration
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
