# Generated by Django 5.0.3 on 2025-01-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.TextField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('expected_transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nominal_code', models.TextField(max_length=15)),
                ('description', models.TextField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('coa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CoaAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.account')),
                ('coa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('financial_statement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='financial_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.financialstatement'),
        ),
    ]
