# Generated by Django 5.0.3 on 2025-01-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='coa_account',
        ),
        migrations.AlterModelTable(
            name='accounttype',
            table='account_type',
        ),
        migrations.AlterModelTable(
            name='chartofaccounts',
            table='chart_of_accounts',
        ),
        migrations.AlterModelTable(
            name='coaaccountlink',
            table='coa_account_link',
        ),
        migrations.AlterModelTable(
            name='financialstatement',
            table='financial_statement',
        ),
        migrations.AlterModelTable(
            name='transactiontype',
            table='transaction_type',
        ),
    ]
