# Generated by Django 5.0.3 on 2025-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_alter_account_table_alter_accounttype_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaaccountlink',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coaaccountlink',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
