# Generated by Django 5.0.3 on 2025-01-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0003_coaaccountlink_end_date_coaaccountlink_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaaccountlink',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coaaccountlink',
            name='start_date',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
