# Generated by Django 5.0.3 on 2025-01-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0004_remove_coaaccountlink_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='full_type_name',
            field=models.TextField(default='Test', max_length=10),
            preserve_default=False,
        ),
    ]
