# Generated by Django 5.0.3 on 2024-12-14 00:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(editable=False, max_length=3, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'legal_entity',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.IntegerField(default=1)),
                ('last_updated_at', models.DateTimeField(null=True)),
                ('last_updated_by', models.IntegerField(null=True)),
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.entitytypes', to_field='entity_id')),
            ],
            options={
                'db_table': 'customer',
                'abstract': False,
            },
        ),
    ]
