# Generated by Django 5.0.3 on 2025-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plaid_public_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
