# Generated by Django 5.0.3 on 2025-02-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_plaid_public_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='plaid_public_token',
            new_name='plaid_access_token',
        ),
    ]
