# Generated by Django 5.0.3 on 2025-02-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_pyrlclient_created_at_and_more'),
        ('customers', '0003_rename_plaid_public_token_customer_plaid_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient'),
            preserve_default=False,
        ),
    ]
