# Generated by Django 5.0.3 on 2025-02-18 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
