# Generated by Django 5.0.3 on 2025-02-21 23:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_pyrlclient_created_at_and_more'),
        ('customers', '0005_customer_customer_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.IntegerField(default=1)),
                ('last_updated_at', models.DateTimeField(null=True)),
                ('last_updated_by', models.IntegerField(null=True)),
                ('customer_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pyrlclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroupCustomerLink',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.IntegerField(default=1)),
                ('last_updated_at', models.DateTimeField(null=True)),
                ('last_updated_by', models.IntegerField(null=True)),
                ('customer_group_customer_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
