# Generated by Django 5.0.3 on 2025-02-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customergroup_customergroupcustomerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
