# Generated by Django 5.0.3 on 2025-02-22 21:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customergroup',
            table='customer_group',
        ),
        migrations.AlterModelTable(
            name='customergroupcustomerlink',
            table='customer_group_customer_link',
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.IntegerField(default=1)),
                ('last_updated_at', models.DateTimeField(null=True)),
                ('last_updated_by', models.IntegerField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('customer_contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(max_length=254)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'customer_contact',
                'abstract': False,
            },
        ),
    ]
