# Generated by Django 5.0.3 on 2025-02-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customergroup_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontact',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
