# Generated by Django 5.0.3 on 2025-02-23 01:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_customer_id_customercontact_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer_contact_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
