# Generated by Django 5.0.3 on 2025-02-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customercontact_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
