# Generated by Django 5.0.3 on 2024-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pyrl_company",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("company_address", models.CharField(max_length=100)),
                ("company_description", models.TextField()),
                ("company_phone", models.CharField(max_length=9)),
                ("company_email_base", models.CharField(max_length=100)),
                ("company_website", models.CharField(max_length=100)),
                ("company_logo", models.ImageField(upload_to="company_logos")),
                ("package_scheme", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="pyrl_user",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=200, verbose_name="password")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
