# Generated by Django 5.0.3 on 2024-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pyrl_company",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("company_address", models.CharField(max_length=100)),
                ("company_description", models.TextField()),
                ("company_phone", models.CharField(max_length=9)),
                ("company_email_base", models.CharField(max_length=100)),
                ("company_website", models.CharField(max_length=100)),
                ("company_logo", models.ImageField(upload_to="company_logos")),
                ("package_scheme", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="pyrl_user",
            fields=[
                (
                    "pid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                ("password", models.CharField(max_length=200, verbose_name="Password")),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(default=False, verbose_name="MFA Enabled"),
                ),
                (
                    "mfa_type",
                    models.CharField(
                        choices=[("sm", "sms"), ("em", "email")],
                        max_length=2,
                        verbose_name="MFA Type",
                    ),
                ),
                ("mfa_code", models.IntegerField(verbose_name="MFA Code")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
