# Generated by Django 5.0.3 on 2024-05-25 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pyrl_user",
        ),
    ]
