# Generated by Django 5.0.3 on 2024-11-19 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyrlClient',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=100)),
                ('client_description', models.TextField()),
                ('client_phone', models.CharField(max_length=9)),
                ('client_email_base', models.CharField(max_length=100)),
                ('client_website', models.CharField(max_length=100)),
                ('client_logo', models.ImageField(upload_to='client_logos')),
                ('package_scheme', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'client',
                'abstract': False,
            },
        ),
    ]
