# Generated by Django 5.0.3 on 2024-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pyrl_user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="pyrl_user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="pyrl_user",
            name="password",
        ),
    ]
