# Generated by Django 5.0.3 on 2024-03-30 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pyrl_users",
            name="company_id",
        ),
    ]
