# Generated by Django 5.0.3 on 2024-11-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='id',
            new_name='client_id',
        ),
    ]
