# Generated by Django 5.0.3 on 2024-12-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_id_pyrlclient_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_email_base',
            new_name='email_base',
        ),
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_phone',
            new_name='telephone_number',
        ),
        migrations.RenameField(
            model_name='pyrlclient',
            old_name='client_website',
            new_name='website',
        ),
        migrations.AddField(
            model_name='pyrlclient',
            name='domain',
            field=models.TextField(null=True),
        ),
    ]
