# Generated by Django 5.0.3 on 2024-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_client_address_pyrlclient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyrlclient',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='pyrlclient',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pyrlclient',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pyrlclient',
            name='email_base',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pyrlclient',
            name='logo',
            field=models.ImageField(null=True, upload_to='client_logos'),
        ),
        migrations.AlterField(
            model_name='pyrlclient',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
