# Generated by Django 5.0.3 on 2024-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pyrl_product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_description", models.TextField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("product_image", models.ImageField(upload_to="static/product_images")),
                ("product_category", models.CharField(max_length=100)),
            ],
        ),
    ]
