# Generated by Django 5.0.7 on 2024-08-23 11:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("created_by", models.IntegerField(default=1)),
                ("last_updated_at", models.DateTimeField(null=True)),
                ("last_updated_by", models.IntegerField(null=True)),
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "invoice_description",
                    models.TextField(blank=True, max_length=30, null=True),
                ),
                ("price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("image", models.ImageField(upload_to="static/product_images")),
                ("category", models.CharField(default="Uncategorized", max_length=100)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.company"
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "abstract": False,
            },
        ),
    ]
