# Generated by Django 5.0.7 on 2024-11-12 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_category",
            fields=[
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("created_by", models.IntegerField(default=1)),
                ("last_updated_at", models.DateTimeField(null=True)),
                ("last_updated_by", models.IntegerField(null=True)),
                (
                    "product_category_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("category_description", models.TextField()),
            ],
            options={
                "db_table": "product_category",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="product_description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pid",
            new_name="product_id",
        ),
    ]
