# Generated by Django 5.0.7 on 2024-11-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_category",
            name="product_category_value",
            field=models.TextField(blank=True, default="CAT", max_length=4),
        ),
    ]
