# Generated by Django 5.0.7 on 2024-11-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        ("products", "0003_product_category_product_category_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_category",
            name="company_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.company",
            ),
            preserve_default=False,
        ),
    ]
