# Generated by Django 5.0.7 on 2024-11-14 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        ("products", "0004_product_category_company_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="product_category",
            new_name="ProductCategory",
        ),
    ]
