# Generated by Django 5.0.3 on 2025-01-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='client_id',
            new_name='client',
        ),
    ]
